-- This file should undo anything in `up.sql`
ALTER TABLE charts
ADD COLUMN name VARCHAR NOT NULL,
ADD COLUMN full_degree FLOAT8 NOT NULL,
ADD COLUMN norm_degree FLOAT8 NOT NULL,
ADD COLUMN speed FLOAT8 NOT NULL,
ADD COLUMN is_retro JSONB NOT NULL,
ADD COLUMN sign VARCHAR NOT NULL,
ADD COLUMN sign_lord VARCHAR NOT NULL,
ADD COLUMN nakshatra VARCHAR NOT NULL,
ADD COLUMN nakshatra_lord VARCHAR NOT NULL,
ADD COLUMN nakshatra_pad INT4 NOT NULL,
ADD COLUMN house INT4 NOT NULL,
ADD COLUMN is_planet_set BOOL NOT NULL,
ADD COLUMN planet_awastha VARCHAR NOT NULL;
