-- Your SQL goes here
ALTER TABLE charts
ADD COLUMN day INT NOT NULL,
ADD COLUMN month INT NOT NULL,
ADD COLUMN year INT NOT NULL,
ADD COLUMN hour INT NOT NULL,
ADD COLUMN min INT NOT NULL,
ADD COLUMN lat FLOAT NOT NULL,
ADD COLUMN lon FLOAT NOT NULL,
ADD COLUMN tzone FLOAT NOT NULL;